apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gpt-2-fine-tuning-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2024-02-18T16:19:03.905017',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A pipeline that fine-tunes
      a GPT-2 model.", "inputs": [{"name": "dataset_name", "type": "String"}, {"name":
      "task", "type": "String"}, {"name": "split", "type": "String"}, {"name": "preprocessed_data_path",
      "type": "String"}, {"name": "test_data", "type": "String"}], "name": "GPT-2
      Fine-Tuning Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: gpt-2-fine-tuning-pipeline
  templates:
  - name: data-processing
    container:
      args: [--dataset_name, ag_news, --task, default, --split, 'train[:10%]']
      image: maamounm/gpt2_preprocess_data:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: generating-output-name
    container:
      args: [test output text generated by gpt2]
      image: maamounm/outputcontainer:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: gpt-2-fine-tuning-pipeline
    dag:
      tasks:
      - {name: data-processing, template: data-processing}
      - name: generating-output-name
        template: generating-output-name
        dependencies: [model-evaluation]
      - name: model-evaluation
        template: model-evaluation
        dependencies: [model-fine-tunning]
      - name: model-fine-tunning
        template: model-fine-tunning
        dependencies: [data-processing]
  - name: model-evaluation
    container:
      args: [model, preprocessed_data.pkl]
      image: maamounm/gpt2-evaluate_model:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: model-fine-tunning
    container:
      args: [preprocessed_data.pkl]
      image: maamounm/gpt2-fine-tuning:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters:
    - {name: dataset_name}
    - {name: task}
    - {name: split}
    - {name: preprocessed_data_path}
    - {name: test_data}
  serviceAccountName: pipeline-runner
